/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlleyView { 'name' : string, 'graveIds' : Array<bigint> }
export type AsyncResult = { 'ok' : null } |
  { 'err' : Error };
export type AsyncResult_1 = { 'ok' : bigint } |
  { 'err' : Error };
export interface CemeteryView {
  'cemeteryName' : string,
  'lastGraveId' : bigint,
  'alleys' : Array<AlleyView>,
}
export interface DeceasedPerson {
  'placeOfDeath' : string,
  'yearOfDeath' : bigint,
  'dateOfDeath' : [] | [Time],
  'lastName' : string,
  'firstName' : string,
}
export type Error = { 'duplicateAlley' : { 'alley' : string } } |
  { 'graveNotFound' : { 'graveId' : bigint } } |
  { 'invariantViolation' : { 'field' : string } } |
  { 'alleyNotFound' : { 'alley' : string } } |
  { 'inconsistentAlleyGraves' : { 'alley' : string, 'graveId' : bigint } } |
  { 'unauthorized' : null } |
  { 'alleyNotEmpty' : { 'alley' : string } };
export type ExternalBlob = Uint8Array;
export interface FooterContent {
  'bankAccountNumber' : string,
  'websiteLink' : string,
  'officeHours' : string,
  'email' : string,
  'address' : string,
  'phoneNumber' : string,
}
export interface GraveOwner {
  'address' : string,
  'phone' : [] | [string],
  'lastName' : string,
  'firstName' : string,
}
export interface GraveRecord {
  'id' : bigint,
  'deceasedPersons' : Array<DeceasedPerson>,
  'status' : GraveStatus,
  'alley' : string,
  'paymentValidUntil' : [] | [Time],
  'owner' : [] | [GraveOwner],
  'plotNumber' : bigint,
}
export type GraveStatus = { 'free' : null } |
  { 'paid' : null } |
  { 'reserved' : null } |
  { 'unpaid' : null };
export interface HomepageHeroContent {
  'backgroundImageUrl' : string,
  'logoImage' : [] | [ExternalBlob],
  'headline' : string,
  'heroBackgroundImage' : [] | [ExternalBlob],
  'introParagraph' : string,
}
export interface PaginatedGravesResult {
  'graves' : Array<GraveRecord>,
  'nextOffset' : [] | [bigint],
  'pageSize' : bigint,
  'totalGraves' : bigint,
}
export interface PrayerForTheDeceased {
  'title' : string,
  'content' : string,
  'memorialPrayer' : string,
}
export interface PublicGraveResult {
  'status' : GraveStatus,
  'alley' : string,
  'yearOfDeath' : [] | [bigint],
  'plotNumber' : bigint,
  'lastName' : string,
  'firstName' : string,
}
export interface PublicGraveShape {
  'status' : GraveStatus,
  'yearOfDeath' : [] | [bigint],
  'lastName' : string,
  'firstName' : string,
}
export interface PublicHtmlSection { 'title' : string, 'content' : string }
export interface PublicTileData {
  'id' : bigint,
  'deceasedPersons' : Array<DeceasedPerson>,
  'status' : GraveStatus,
  'alley' : string,
  'plotNumber' : bigint,
}
export interface SiteContent {
  'logoImage' : [] | [ExternalBlob],
  'cemeteryInformation' : PublicHtmlSection,
  'prayerForTheDeceased' : PrayerForTheDeceased,
  'gravesDeclaration' : PublicHtmlSection,
  'footer' : FooterContent,
  'homepageHero' : HomepageHeroContent,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlley' : ActorMethod<[string], AsyncResult>,
  'addGrave' : ActorMethod<[string, bigint], AsyncResult_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllGraves' : ActorMethod<[], Array<GraveRecord>>,
  'getAvailableGraves' : ActorMethod<[], Array<GraveRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCemeteryInformation' : ActorMethod<[], PublicHtmlSection>,
  'getCemeteryState' : ActorMethod<[], CemeteryView>,
  'getCemeteryStateWithoutVerification' : ActorMethod<[], CemeteryView>,
  'getFooterContent' : ActorMethod<[], FooterContent>,
  'getGrave' : ActorMethod<[bigint], [] | [GraveRecord]>,
  'getGraveStatistics' : ActorMethod<
    [],
    {
      'total' : bigint,
      'free' : bigint,
      'paid' : bigint,
      'reserved' : bigint,
      'unpaid' : bigint,
    }
  >,
  'getGravesByAlley' : ActorMethod<[string], Array<GraveRecord>>,
  'getGravesDeclaration' : ActorMethod<[], PublicHtmlSection>,
  'getHomepageHeroContent' : ActorMethod<[], HomepageHeroContent>,
  'getPaginatedGraves' : ActorMethod<[bigint, bigint], PaginatedGravesResult>,
  'getParishContactEmail' : ActorMethod<[], string>,
  'getPrayerForTheDeceased' : ActorMethod<[], PrayerForTheDeceased>,
  'getPublicGraves' : ActorMethod<[], Array<PublicGraveShape>>,
  'getPublicTiles' : ActorMethod<[], Array<PublicTileData>>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getSurnamesForAutocomplete' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAlley' : ActorMethod<[string], AsyncResult>,
  'removeGrave' : ActorMethod<[bigint], AsyncResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchGraves' : ActorMethod<
    [
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [GraveStatus],
      [] | [string],
    ],
    Array<GraveRecord>
  >,
  'searchPublicGravesWithLocation' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<PublicGraveResult>
  >,
  'updateCemeteryInformation' : ActorMethod<[PublicHtmlSection], undefined>,
  'updateFooterContent' : ActorMethod<[FooterContent], undefined>,
  'updateGrave' : ActorMethod<[bigint, GraveRecord], AsyncResult>,
  'updateGravesDeclaration' : ActorMethod<[PublicHtmlSection], undefined>,
  'updateHomepageHeroContent' : ActorMethod<[HomepageHeroContent], undefined>,
  'updateLogoImage' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updatePrayerForTheDeceased' : ActorMethod<[PrayerForTheDeceased], undefined>,
  'updateSiteContent' : ActorMethod<[SiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];