/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'duplicateAlley' : IDL.Record({ 'alley' : IDL.Text }),
  'graveNotFound' : IDL.Record({ 'graveId' : IDL.Nat }),
  'invariantViolation' : IDL.Record({ 'field' : IDL.Text }),
  'alleyNotFound' : IDL.Record({ 'alley' : IDL.Text }),
  'inconsistentAlleyGraves' : IDL.Record({
    'alley' : IDL.Text,
    'graveId' : IDL.Nat,
  }),
  'unauthorized' : IDL.Null,
  'alleyNotEmpty' : IDL.Record({ 'alley' : IDL.Text }),
});
export const AsyncResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const AsyncResult_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DeceasedPerson = IDL.Record({
  'placeOfDeath' : IDL.Text,
  'yearOfDeath' : IDL.Int,
  'dateOfDeath' : IDL.Opt(Time),
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const GraveStatus = IDL.Variant({
  'free' : IDL.Null,
  'paid' : IDL.Null,
  'reserved' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const GraveOwner = IDL.Record({
  'address' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const GraveRecord = IDL.Record({
  'id' : IDL.Nat,
  'deceasedPersons' : IDL.Vec(DeceasedPerson),
  'status' : GraveStatus,
  'alley' : IDL.Text,
  'paymentValidUntil' : IDL.Opt(Time),
  'owner' : IDL.Opt(GraveOwner),
  'plotNumber' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const PublicHtmlSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const AlleyView = IDL.Record({
  'name' : IDL.Text,
  'graveIds' : IDL.Vec(IDL.Nat),
});
export const CemeteryView = IDL.Record({
  'cemeteryName' : IDL.Text,
  'lastGraveId' : IDL.Nat,
  'alleys' : IDL.Vec(AlleyView),
});
export const FooterContent = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'websiteLink' : IDL.Text,
  'officeHours' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const HomepageHeroContent = IDL.Record({
  'backgroundImageUrl' : IDL.Text,
  'logoImage' : IDL.Opt(ExternalBlob),
  'headline' : IDL.Text,
  'heroBackgroundImage' : IDL.Opt(ExternalBlob),
  'introParagraph' : IDL.Text,
});
export const PaginatedGravesResult = IDL.Record({
  'graves' : IDL.Vec(GraveRecord),
  'nextOffset' : IDL.Opt(IDL.Nat),
  'pageSize' : IDL.Nat,
  'totalGraves' : IDL.Nat,
});
export const PrayerForTheDeceased = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'memorialPrayer' : IDL.Text,
});
export const PublicGraveShape = IDL.Record({
  'status' : GraveStatus,
  'yearOfDeath' : IDL.Opt(IDL.Int),
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const PublicTileData = IDL.Record({
  'id' : IDL.Nat,
  'deceasedPersons' : IDL.Vec(DeceasedPerson),
  'status' : GraveStatus,
  'alley' : IDL.Text,
  'plotNumber' : IDL.Nat,
});
export const SiteContent = IDL.Record({
  'logoImage' : IDL.Opt(ExternalBlob),
  'cemeteryInformation' : PublicHtmlSection,
  'prayerForTheDeceased' : PrayerForTheDeceased,
  'gravesDeclaration' : PublicHtmlSection,
  'footer' : FooterContent,
  'homepageHero' : HomepageHeroContent,
});
export const PublicGraveResult = IDL.Record({
  'status' : GraveStatus,
  'alley' : IDL.Text,
  'yearOfDeath' : IDL.Opt(IDL.Int),
  'plotNumber' : IDL.Nat,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlley' : IDL.Func([IDL.Text], [AsyncResult], []),
  'addGrave' : IDL.Func([IDL.Text, IDL.Nat], [AsyncResult_1], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllGraves' : IDL.Func([], [IDL.Vec(GraveRecord)], ['query']),
  'getAvailableGraves' : IDL.Func([], [IDL.Vec(GraveRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCemeteryInformation' : IDL.Func([], [PublicHtmlSection], ['query']),
  'getCemeteryState' : IDL.Func([], [CemeteryView], ['query']),
  'getCemeteryStateWithoutVerification' : IDL.Func(
      [],
      [CemeteryView],
      ['query'],
    ),
  'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
  'getGrave' : IDL.Func([IDL.Nat], [IDL.Opt(GraveRecord)], ['query']),
  'getGraveStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'free' : IDL.Nat,
          'paid' : IDL.Nat,
          'reserved' : IDL.Nat,
          'unpaid' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getGravesByAlley' : IDL.Func([IDL.Text], [IDL.Vec(GraveRecord)], ['query']),
  'getGravesDeclaration' : IDL.Func([], [PublicHtmlSection], ['query']),
  'getHomepageHeroContent' : IDL.Func([], [HomepageHeroContent], ['query']),
  'getPaginatedGraves' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedGravesResult],
      ['query'],
    ),
  'getParishContactEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getPrayerForTheDeceased' : IDL.Func([], [PrayerForTheDeceased], ['query']),
  'getPublicGraves' : IDL.Func([], [IDL.Vec(PublicGraveShape)], ['query']),
  'getPublicTiles' : IDL.Func([], [IDL.Vec(PublicTileData)], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getSurnamesForAutocomplete' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAlley' : IDL.Func([IDL.Text], [AsyncResult], []),
  'removeGrave' : IDL.Func([IDL.Nat], [AsyncResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchGraves' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
        IDL.Opt(GraveStatus),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(GraveRecord)],
      ['query'],
    ),
  'searchPublicGravesWithLocation' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Vec(PublicGraveResult)],
      ['query'],
    ),
  'updateCemeteryInformation' : IDL.Func([PublicHtmlSection], [], []),
  'updateFooterContent' : IDL.Func([FooterContent], [], []),
  'updateGrave' : IDL.Func([IDL.Nat, GraveRecord], [AsyncResult], []),
  'updateGravesDeclaration' : IDL.Func([PublicHtmlSection], [], []),
  'updateHomepageHeroContent' : IDL.Func([HomepageHeroContent], [], []),
  'updateLogoImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'updatePrayerForTheDeceased' : IDL.Func([PrayerForTheDeceased], [], []),
  'updateSiteContent' : IDL.Func([SiteContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'duplicateAlley' : IDL.Record({ 'alley' : IDL.Text }),
    'graveNotFound' : IDL.Record({ 'graveId' : IDL.Nat }),
    'invariantViolation' : IDL.Record({ 'field' : IDL.Text }),
    'alleyNotFound' : IDL.Record({ 'alley' : IDL.Text }),
    'inconsistentAlleyGraves' : IDL.Record({
      'alley' : IDL.Text,
      'graveId' : IDL.Nat,
    }),
    'unauthorized' : IDL.Null,
    'alleyNotEmpty' : IDL.Record({ 'alley' : IDL.Text }),
  });
  const AsyncResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const AsyncResult_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DeceasedPerson = IDL.Record({
    'placeOfDeath' : IDL.Text,
    'yearOfDeath' : IDL.Int,
    'dateOfDeath' : IDL.Opt(Time),
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const GraveStatus = IDL.Variant({
    'free' : IDL.Null,
    'paid' : IDL.Null,
    'reserved' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const GraveOwner = IDL.Record({
    'address' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const GraveRecord = IDL.Record({
    'id' : IDL.Nat,
    'deceasedPersons' : IDL.Vec(DeceasedPerson),
    'status' : GraveStatus,
    'alley' : IDL.Text,
    'paymentValidUntil' : IDL.Opt(Time),
    'owner' : IDL.Opt(GraveOwner),
    'plotNumber' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const PublicHtmlSection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const AlleyView = IDL.Record({
    'name' : IDL.Text,
    'graveIds' : IDL.Vec(IDL.Nat),
  });
  const CemeteryView = IDL.Record({
    'cemeteryName' : IDL.Text,
    'lastGraveId' : IDL.Nat,
    'alleys' : IDL.Vec(AlleyView),
  });
  const FooterContent = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'websiteLink' : IDL.Text,
    'officeHours' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const HomepageHeroContent = IDL.Record({
    'backgroundImageUrl' : IDL.Text,
    'logoImage' : IDL.Opt(ExternalBlob),
    'headline' : IDL.Text,
    'heroBackgroundImage' : IDL.Opt(ExternalBlob),
    'introParagraph' : IDL.Text,
  });
  const PaginatedGravesResult = IDL.Record({
    'graves' : IDL.Vec(GraveRecord),
    'nextOffset' : IDL.Opt(IDL.Nat),
    'pageSize' : IDL.Nat,
    'totalGraves' : IDL.Nat,
  });
  const PrayerForTheDeceased = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'memorialPrayer' : IDL.Text,
  });
  const PublicGraveShape = IDL.Record({
    'status' : GraveStatus,
    'yearOfDeath' : IDL.Opt(IDL.Int),
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const PublicTileData = IDL.Record({
    'id' : IDL.Nat,
    'deceasedPersons' : IDL.Vec(DeceasedPerson),
    'status' : GraveStatus,
    'alley' : IDL.Text,
    'plotNumber' : IDL.Nat,
  });
  const SiteContent = IDL.Record({
    'logoImage' : IDL.Opt(ExternalBlob),
    'cemeteryInformation' : PublicHtmlSection,
    'prayerForTheDeceased' : PrayerForTheDeceased,
    'gravesDeclaration' : PublicHtmlSection,
    'footer' : FooterContent,
    'homepageHero' : HomepageHeroContent,
  });
  const PublicGraveResult = IDL.Record({
    'status' : GraveStatus,
    'alley' : IDL.Text,
    'yearOfDeath' : IDL.Opt(IDL.Int),
    'plotNumber' : IDL.Nat,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlley' : IDL.Func([IDL.Text], [AsyncResult], []),
    'addGrave' : IDL.Func([IDL.Text, IDL.Nat], [AsyncResult_1], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllGraves' : IDL.Func([], [IDL.Vec(GraveRecord)], ['query']),
    'getAvailableGraves' : IDL.Func([], [IDL.Vec(GraveRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCemeteryInformation' : IDL.Func([], [PublicHtmlSection], ['query']),
    'getCemeteryState' : IDL.Func([], [CemeteryView], ['query']),
    'getCemeteryStateWithoutVerification' : IDL.Func(
        [],
        [CemeteryView],
        ['query'],
      ),
    'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
    'getGrave' : IDL.Func([IDL.Nat], [IDL.Opt(GraveRecord)], ['query']),
    'getGraveStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'free' : IDL.Nat,
            'paid' : IDL.Nat,
            'reserved' : IDL.Nat,
            'unpaid' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getGravesByAlley' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GraveRecord)],
        ['query'],
      ),
    'getGravesDeclaration' : IDL.Func([], [PublicHtmlSection], ['query']),
    'getHomepageHeroContent' : IDL.Func([], [HomepageHeroContent], ['query']),
    'getPaginatedGraves' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedGravesResult],
        ['query'],
      ),
    'getParishContactEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getPrayerForTheDeceased' : IDL.Func([], [PrayerForTheDeceased], ['query']),
    'getPublicGraves' : IDL.Func([], [IDL.Vec(PublicGraveShape)], ['query']),
    'getPublicTiles' : IDL.Func([], [IDL.Vec(PublicTileData)], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getSurnamesForAutocomplete' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAlley' : IDL.Func([IDL.Text], [AsyncResult], []),
    'removeGrave' : IDL.Func([IDL.Nat], [AsyncResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchGraves' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
          IDL.Opt(GraveStatus),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(GraveRecord)],
        ['query'],
      ),
    'searchPublicGravesWithLocation' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
        [IDL.Vec(PublicGraveResult)],
        ['query'],
      ),
    'updateCemeteryInformation' : IDL.Func([PublicHtmlSection], [], []),
    'updateFooterContent' : IDL.Func([FooterContent], [], []),
    'updateGrave' : IDL.Func([IDL.Nat, GraveRecord], [AsyncResult], []),
    'updateGravesDeclaration' : IDL.Func([PublicHtmlSection], [], []),
    'updateHomepageHeroContent' : IDL.Func([HomepageHeroContent], [], []),
    'updateLogoImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'updatePrayerForTheDeceased' : IDL.Func([PrayerForTheDeceased], [], []),
    'updateSiteContent' : IDL.Func([SiteContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };