/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PublicHtmlSection {
    title: string;
    content: string;
}
export interface PublicTileData {
    id: bigint;
    deceasedPersons: Array<DeceasedPerson>;
    status: GraveStatus;
    alley: string;
    plotNumber: bigint;
}
export interface GraveRecord {
    id: bigint;
    deceasedPersons: Array<DeceasedPerson>;
    status: GraveStatus;
    alley: string;
    paymentValidUntil?: Time;
    owner?: GraveOwner;
    plotNumber: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Error_ = {
    __kind__: "duplicateAlley";
    duplicateAlley: {
        alley: string;
    };
} | {
    __kind__: "graveNotFound";
    graveNotFound: {
        graveId: bigint;
    };
} | {
    __kind__: "invariantViolation";
    invariantViolation: {
        field: string;
    };
} | {
    __kind__: "alleyNotFound";
    alleyNotFound: {
        alley: string;
    };
} | {
    __kind__: "inconsistentAlleyGraves";
    inconsistentAlleyGraves: {
        alley: string;
        graveId: bigint;
    };
} | {
    __kind__: "alleyNotEmpty";
    alleyNotEmpty: {
        alley: string;
    };
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaginatedGravesResult {
    graves: Array<GraveRecord>;
    nextOffset?: bigint;
    pageSize: bigint;
    totalGraves: bigint;
}
export interface GraveOwner {
    address: string;
    phone?: string;
    lastName: string;
    firstName: string;
}
export interface DeceasedPerson {
    placeOfDeath: string;
    yearOfDeath: bigint;
    dateOfDeath?: Time;
    lastName: string;
    firstName: string;
}
export interface CemeteryView {
    cemeteryName: string;
    lastGraveId: bigint;
    alleys: Array<AlleyView>;
}
export type AsyncResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PublicGraveShape {
    status: GraveStatus;
    yearOfDeath?: bigint;
    lastName: string;
    firstName: string;
}
export interface HomepageHeroContent {
    backgroundImageUrl: string;
    logoImage?: ExternalBlob;
    headline: string;
    heroBackgroundImage?: ExternalBlob;
    introParagraph: string;
}
export interface FooterContent {
    bankAccountNumber: string;
    websiteLink: string;
    officeHours: string;
    email: string;
    address: string;
    phoneNumber: string;
}
export type AsyncResult_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SiteContent {
    logoImage?: ExternalBlob;
    cemeteryInformation: PublicHtmlSection;
    prayerForTheDeceased: PublicHtmlSection;
    gravesDeclaration: PublicHtmlSection;
    footer: FooterContent;
    homepageHero: HomepageHeroContent;
}
export interface AlleyView {
    name: string;
    graveIds: Array<bigint>;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum GraveStatus {
    free = "free",
    paid = "paid",
    reserved = "reserved",
    unpaid = "unpaid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAlley(name: string): Promise<AsyncResult>;
    addGrave(alley: string, plotNumber: bigint): Promise<AsyncResult_1>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllGraves(): Promise<Array<GraveRecord>>;
    getAvailableGraves(): Promise<Array<GraveRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCemeteryInformation(): Promise<PublicHtmlSection>;
    getCemeteryState(): Promise<CemeteryView>;
    getCemeteryStateWithoutVerification(): Promise<CemeteryView>;
    getFooterContent(): Promise<FooterContent>;
    getGrave(id: bigint): Promise<GraveRecord | null>;
    getGraveStatistics(): Promise<{
        total: bigint;
        free: bigint;
        paid: bigint;
        reserved: bigint;
        unpaid: bigint;
    }>;
    getGravesByAlley(alley: string): Promise<Array<GraveRecord>>;
    getGravesDeclaration(): Promise<PublicHtmlSection>;
    getHomepageHeroContent(): Promise<HomepageHeroContent>;
    getPaginatedGraves(offset: bigint, pageSize: bigint): Promise<PaginatedGravesResult>;
    getParishContactEmail(): Promise<string>;
    getPrayerForTheDeceased(): Promise<PublicHtmlSection>;
    getPublicGraves(): Promise<Array<PublicGraveShape>>;
    getPublicGravesByAlley(alley: string): Promise<Array<PublicGraveShape>>;
    getPublicTiles(): Promise<Array<PublicTileData>>;
    getSiteContent(): Promise<SiteContent>;
    getSurnamesForAutocomplete(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeAlley(name: string): Promise<AsyncResult>;
    removeGrave(id: bigint): Promise<AsyncResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchGraves(surname: string | null, yearOfDeath: bigint | null, owner: string | null, status: GraveStatus | null, locality: string | null): Promise<Array<GraveRecord>>;
    searchPublicGraves(surname: string | null, yearOfDeath: bigint | null): Promise<Array<PublicGraveShape>>;
    updateCemeteryInformation(newSection: PublicHtmlSection): Promise<void>;
    updateFooterContent(newFooterContent: FooterContent): Promise<void>;
    updateGrave(id: bigint, updatedRecord: GraveRecord): Promise<AsyncResult>;
    updateGravesDeclaration(newSection: PublicHtmlSection): Promise<void>;
    updateHomepageHeroContent(newContent: HomepageHeroContent): Promise<void>;
    updateLogoImage(newLogo: ExternalBlob | null): Promise<void>;
    updatePrayerForTheDeceased(newSection: PublicHtmlSection): Promise<void>;
    updateSiteContent(newContent: SiteContent): Promise<void>;
}
import type { AsyncResult as _AsyncResult, AsyncResult_1 as _AsyncResult_1, DeceasedPerson as _DeceasedPerson, Error as _Error, ExternalBlob as _ExternalBlob, FooterContent as _FooterContent, GraveOwner as _GraveOwner, GraveRecord as _GraveRecord, GraveStatus as _GraveStatus, HomepageHeroContent as _HomepageHeroContent, PaginatedGravesResult as _PaginatedGravesResult, PublicGraveShape as _PublicGraveShape, PublicHtmlSection as _PublicHtmlSection, PublicTileData as _PublicTileData, SiteContent as _SiteContent, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAlley(arg0: string): Promise<AsyncResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlley(arg0);
                return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlley(arg0);
            return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addGrave(arg0: string, arg1: bigint): Promise<AsyncResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addGrave(arg0, arg1);
                return from_candid_AsyncResult_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGrave(arg0, arg1);
            return from_candid_AsyncResult_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllGraves(): Promise<Array<GraveRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGraves();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGraves();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableGraves(): Promise<Array<GraveRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableGraves();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableGraves();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCemeteryInformation(): Promise<PublicHtmlSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getCemeteryInformation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCemeteryInformation();
            return result;
        }
    }
    async getCemeteryState(): Promise<CemeteryView> {
        if (this.processError) {
            try {
                const result = await this.actor.getCemeteryState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCemeteryState();
            return result;
        }
    }
    async getCemeteryStateWithoutVerification(): Promise<CemeteryView> {
        if (this.processError) {
            try {
                const result = await this.actor.getCemeteryStateWithoutVerification();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCemeteryStateWithoutVerification();
            return result;
        }
    }
    async getFooterContent(): Promise<FooterContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getFooterContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFooterContent();
            return result;
        }
    }
    async getGrave(arg0: bigint): Promise<GraveRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrave(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrave(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGraveStatistics(): Promise<{
        total: bigint;
        free: bigint;
        paid: bigint;
        reserved: bigint;
        unpaid: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGraveStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGraveStatistics();
            return result;
        }
    }
    async getGravesByAlley(arg0: string): Promise<Array<GraveRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGravesByAlley(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGravesByAlley(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGravesDeclaration(): Promise<PublicHtmlSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getGravesDeclaration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGravesDeclaration();
            return result;
        }
    }
    async getHomepageHeroContent(): Promise<HomepageHeroContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomepageHeroContent();
                return from_candid_HomepageHeroContent_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomepageHeroContent();
            return from_candid_HomepageHeroContent_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaginatedGraves(arg0: bigint, arg1: bigint): Promise<PaginatedGravesResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedGraves(arg0, arg1);
                return from_candid_PaginatedGravesResult_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedGraves(arg0, arg1);
            return from_candid_PaginatedGravesResult_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParishContactEmail(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getParishContactEmail();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParishContactEmail();
            return result;
        }
    }
    async getPrayerForTheDeceased(): Promise<PublicHtmlSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrayerForTheDeceased();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrayerForTheDeceased();
            return result;
        }
    }
    async getPublicGraves(): Promise<Array<PublicGraveShape>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicGraves();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicGraves();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicGravesByAlley(arg0: string): Promise<Array<PublicGraveShape>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicGravesByAlley(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicGravesByAlley(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicTiles(): Promise<Array<PublicTileData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicTiles();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicTiles();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteContent(): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent();
                return from_candid_SiteContent_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent();
            return from_candid_SiteContent_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSurnamesForAutocomplete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurnamesForAutocomplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurnamesForAutocomplete();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeAlley(arg0: string): Promise<AsyncResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAlley(arg0);
                return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAlley(arg0);
            return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeGrave(arg0: bigint): Promise<AsyncResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGrave(arg0);
                return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGrave(arg0);
            return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchGraves(arg0: string | null, arg1: bigint | null, arg2: string | null, arg3: GraveStatus | null, arg4: string | null): Promise<Array<GraveRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGraves(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg4));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGraves(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg4));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchPublicGraves(arg0: string | null, arg1: bigint | null): Promise<Array<PublicGraveShape>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPublicGraves(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPublicGraves(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCemeteryInformation(arg0: PublicHtmlSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCemeteryInformation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCemeteryInformation(arg0);
            return result;
        }
    }
    async updateFooterContent(arg0: FooterContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFooterContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFooterContent(arg0);
            return result;
        }
    }
    async updateGrave(arg0: bigint, arg1: GraveRecord): Promise<AsyncResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGrave(arg0, to_candid_GraveRecord_n57(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGrave(arg0, to_candid_GraveRecord_n57(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AsyncResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGravesDeclaration(arg0: PublicHtmlSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGravesDeclaration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGravesDeclaration(arg0);
            return result;
        }
    }
    async updateHomepageHeroContent(arg0: HomepageHeroContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomepageHeroContent(await to_candid_HomepageHeroContent_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomepageHeroContent(await to_candid_HomepageHeroContent_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLogoImage(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogoImage(await to_candid_opt_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogoImage(await to_candid_opt_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePrayerForTheDeceased(arg0: PublicHtmlSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrayerForTheDeceased(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrayerForTheDeceased(arg0);
            return result;
        }
    }
    async updateSiteContent(arg0: SiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteContent(await to_candid_SiteContent_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteContent(await to_candid_SiteContent_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AsyncResult_1_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AsyncResult_1): AsyncResult_1 {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_AsyncResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AsyncResult): AsyncResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DeceasedPerson_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeceasedPerson): DeceasedPerson {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GraveOwner_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GraveOwner): GraveOwner {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_GraveRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GraveRecord): GraveRecord {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_GraveStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GraveStatus): GraveStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_HomepageHeroContent_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomepageHeroContent): Promise<HomepageHeroContent> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedGravesResult_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedGravesResult): PaginatedGravesResult {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PublicGraveShape_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicGraveShape): PublicGraveShape {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PublicTileData_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicTileData): PublicTileData {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_SiteContent_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteContent): Promise<SiteContent> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GraveOwner]): GraveOwner | null {
    return value.length === 0 ? null : from_candid_GraveOwner_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GraveRecord]): GraveRecord | null {
    return value.length === 0 ? null : from_candid_GraveRecord_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    deceasedPersons: Array<_DeceasedPerson>;
    status: _GraveStatus;
    alley: string;
    paymentValidUntil: [] | [_Time];
    owner: [] | [_GraveOwner];
    plotNumber: bigint;
}): {
    id: bigint;
    deceasedPersons: Array<DeceasedPerson>;
    status: GraveStatus;
    alley: string;
    paymentValidUntil?: Time;
    owner?: GraveOwner;
    plotNumber: bigint;
} {
    return {
        id: value.id,
        deceasedPersons: from_candid_vec_n19(_uploadFile, _downloadFile, value.deceasedPersons),
        status: from_candid_GraveStatus_n23(_uploadFile, _downloadFile, value.status),
        alley: value.alley,
        paymentValidUntil: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.paymentValidUntil)),
        owner: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.owner)),
        plotNumber: value.plotNumber
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfDeath: string;
    yearOfDeath: bigint;
    dateOfDeath: [] | [_Time];
    lastName: string;
    firstName: string;
}): {
    placeOfDeath: string;
    yearOfDeath: bigint;
    dateOfDeath?: Time;
    lastName: string;
    firstName: string;
} {
    return {
        placeOfDeath: value.placeOfDeath,
        yearOfDeath: value.yearOfDeath,
        dateOfDeath: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.dateOfDeath)),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    address: string;
    phone: [] | [string];
    lastName: string;
    firstName: string;
}): {
    address: string;
    phone?: string;
    lastName: string;
    firstName: string;
} {
    return {
        address: value.address,
        phone: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.phone)),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.email))
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundImageUrl: string;
    logoImage: [] | [_ExternalBlob];
    headline: string;
    heroBackgroundImage: [] | [_ExternalBlob];
    introParagraph: string;
}): Promise<{
    backgroundImageUrl: string;
    logoImage?: ExternalBlob;
    headline: string;
    heroBackgroundImage?: ExternalBlob;
    introParagraph: string;
}> {
    return {
        backgroundImageUrl: value.backgroundImageUrl,
        logoImage: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.logoImage)),
        headline: value.headline,
        heroBackgroundImage: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.heroBackgroundImage)),
        introParagraph: value.introParagraph
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    graves: Array<_GraveRecord>;
    nextOffset: [] | [bigint];
    pageSize: bigint;
    totalGraves: bigint;
}): {
    graves: Array<GraveRecord>;
    nextOffset?: bigint;
    pageSize: bigint;
    totalGraves: bigint;
} {
    return {
        graves: from_candid_vec_n16(_uploadFile, _downloadFile, value.graves),
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        pageSize: value.pageSize,
        totalGraves: value.totalGraves
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _GraveStatus;
    yearOfDeath: [] | [bigint];
    lastName: string;
    firstName: string;
}): {
    status: GraveStatus;
    yearOfDeath?: bigint;
    lastName: string;
    firstName: string;
} {
    return {
        status: from_candid_GraveStatus_n23(_uploadFile, _downloadFile, value.status),
        yearOfDeath: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.yearOfDeath)),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    deceasedPersons: Array<_DeceasedPerson>;
    status: _GraveStatus;
    alley: string;
    plotNumber: bigint;
}): {
    id: bigint;
    deceasedPersons: Array<DeceasedPerson>;
    status: GraveStatus;
    alley: string;
    plotNumber: bigint;
} {
    return {
        id: value.id,
        deceasedPersons: from_candid_vec_n19(_uploadFile, _downloadFile, value.deceasedPersons),
        status: from_candid_GraveStatus_n23(_uploadFile, _downloadFile, value.status),
        alley: value.alley,
        plotNumber: value.plotNumber
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logoImage: [] | [_ExternalBlob];
    cemeteryInformation: _PublicHtmlSection;
    prayerForTheDeceased: _PublicHtmlSection;
    gravesDeclaration: _PublicHtmlSection;
    footer: _FooterContent;
    homepageHero: _HomepageHeroContent;
}): Promise<{
    logoImage?: ExternalBlob;
    cemeteryInformation: PublicHtmlSection;
    prayerForTheDeceased: PublicHtmlSection;
    gravesDeclaration: PublicHtmlSection;
    footer: FooterContent;
    homepageHero: HomepageHeroContent;
}> {
    return {
        logoImage: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.logoImage)),
        cemeteryInformation: value.cemeteryInformation,
        prayerForTheDeceased: value.prayerForTheDeceased,
        gravesDeclaration: value.gravesDeclaration,
        footer: value.footer,
        homepageHero: await from_candid_HomepageHeroContent_n35(_uploadFile, _downloadFile, value.homepageHero)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duplicateAlley: {
        alley: string;
    };
} | {
    graveNotFound: {
        graveId: bigint;
    };
} | {
    invariantViolation: {
        field: string;
    };
} | {
    alleyNotFound: {
        alley: string;
    };
} | {
    inconsistentAlleyGraves: {
        alley: string;
        graveId: bigint;
    };
} | {
    alleyNotEmpty: {
        alley: string;
    };
}): {
    __kind__: "duplicateAlley";
    duplicateAlley: {
        alley: string;
    };
} | {
    __kind__: "graveNotFound";
    graveNotFound: {
        graveId: bigint;
    };
} | {
    __kind__: "invariantViolation";
    invariantViolation: {
        field: string;
    };
} | {
    __kind__: "alleyNotFound";
    alleyNotFound: {
        alley: string;
    };
} | {
    __kind__: "inconsistentAlleyGraves";
    inconsistentAlleyGraves: {
        alley: string;
        graveId: bigint;
    };
} | {
    __kind__: "alleyNotEmpty";
    alleyNotEmpty: {
        alley: string;
    };
} {
    return "duplicateAlley" in value ? {
        __kind__: "duplicateAlley",
        duplicateAlley: value.duplicateAlley
    } : "graveNotFound" in value ? {
        __kind__: "graveNotFound",
        graveNotFound: value.graveNotFound
    } : "invariantViolation" in value ? {
        __kind__: "invariantViolation",
        invariantViolation: value.invariantViolation
    } : "alleyNotFound" in value ? {
        __kind__: "alleyNotFound",
        alleyNotFound: value.alleyNotFound
    } : "inconsistentAlleyGraves" in value ? {
        __kind__: "inconsistentAlleyGraves",
        inconsistentAlleyGraves: value.inconsistentAlleyGraves
    } : "alleyNotEmpty" in value ? {
        __kind__: "alleyNotEmpty",
        alleyNotEmpty: value.alleyNotEmpty
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free: null;
} | {
    paid: null;
} | {
    reserved: null;
} | {
    unpaid: null;
}): GraveStatus {
    return "free" in value ? GraveStatus.free : "paid" in value ? GraveStatus.paid : "reserved" in value ? GraveStatus.reserved : "unpaid" in value ? GraveStatus.unpaid : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GraveRecord>): Array<GraveRecord> {
    return value.map((x)=>from_candid_GraveRecord_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeceasedPerson>): Array<DeceasedPerson> {
    return value.map((x)=>from_candid_DeceasedPerson_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicGraveShape>): Array<PublicGraveShape> {
    return value.map((x)=>from_candid_PublicGraveShape_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicTileData>): Array<PublicTileData> {
    return value.map((x)=>from_candid_PublicTileData_n46(_uploadFile, _downloadFile, x));
}
function to_candid_DeceasedPerson_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeceasedPerson): _DeceasedPerson {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GraveOwner_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GraveOwner): _GraveOwner {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_GraveRecord_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GraveRecord): _GraveRecord {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_GraveStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GraveStatus): _GraveStatus {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
async function to_candid_HomepageHeroContent_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomepageHeroContent): Promise<_HomepageHeroContent> {
    return await to_candid_record_n65(_uploadFile, _downloadFile, value);
}
async function to_candid_SiteContent_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteContent): Promise<_SiteContent> {
    return await to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GraveStatus | null): [] | [_GraveStatus] {
    return value === null ? candid_none() : candid_some(to_candid_GraveStatus_n55(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n66(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    deceasedPersons: Array<DeceasedPerson>;
    status: GraveStatus;
    alley: string;
    paymentValidUntil?: Time;
    owner?: GraveOwner;
    plotNumber: bigint;
}): {
    id: bigint;
    deceasedPersons: Array<_DeceasedPerson>;
    status: _GraveStatus;
    alley: string;
    paymentValidUntil: [] | [_Time];
    owner: [] | [_GraveOwner];
    plotNumber: bigint;
} {
    return {
        id: value.id,
        deceasedPersons: to_candid_vec_n59(_uploadFile, _downloadFile, value.deceasedPersons),
        status: to_candid_GraveStatus_n55(_uploadFile, _downloadFile, value.status),
        alley: value.alley,
        paymentValidUntil: value.paymentValidUntil ? candid_some(value.paymentValidUntil) : candid_none(),
        owner: value.owner ? candid_some(to_candid_GraveOwner_n62(_uploadFile, _downloadFile, value.owner)) : candid_none(),
        plotNumber: value.plotNumber
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfDeath: string;
    yearOfDeath: bigint;
    dateOfDeath?: Time;
    lastName: string;
    firstName: string;
}): {
    placeOfDeath: string;
    yearOfDeath: bigint;
    dateOfDeath: [] | [_Time];
    lastName: string;
    firstName: string;
} {
    return {
        placeOfDeath: value.placeOfDeath,
        yearOfDeath: value.yearOfDeath,
        dateOfDeath: value.dateOfDeath ? candid_some(value.dateOfDeath) : candid_none(),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    address: string;
    phone?: string;
    lastName: string;
    firstName: string;
}): {
    address: string;
    phone: [] | [string];
    lastName: string;
    firstName: string;
} {
    return {
        address: value.address,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
async function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundImageUrl: string;
    logoImage?: ExternalBlob;
    headline: string;
    heroBackgroundImage?: ExternalBlob;
    introParagraph: string;
}): Promise<{
    backgroundImageUrl: string;
    logoImage: [] | [_ExternalBlob];
    headline: string;
    heroBackgroundImage: [] | [_ExternalBlob];
    introParagraph: string;
}> {
    return {
        backgroundImageUrl: value.backgroundImageUrl,
        logoImage: value.logoImage ? candid_some(await to_candid_ExternalBlob_n66(_uploadFile, _downloadFile, value.logoImage)) : candid_none(),
        headline: value.headline,
        heroBackgroundImage: value.heroBackgroundImage ? candid_some(await to_candid_ExternalBlob_n66(_uploadFile, _downloadFile, value.heroBackgroundImage)) : candid_none(),
        introParagraph: value.introParagraph
    };
}
async function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logoImage?: ExternalBlob;
    cemeteryInformation: PublicHtmlSection;
    prayerForTheDeceased: PublicHtmlSection;
    gravesDeclaration: PublicHtmlSection;
    footer: FooterContent;
    homepageHero: HomepageHeroContent;
}): Promise<{
    logoImage: [] | [_ExternalBlob];
    cemeteryInformation: _PublicHtmlSection;
    prayerForTheDeceased: _PublicHtmlSection;
    gravesDeclaration: _PublicHtmlSection;
    footer: _FooterContent;
    homepageHero: _HomepageHeroContent;
}> {
    return {
        logoImage: value.logoImage ? candid_some(await to_candid_ExternalBlob_n66(_uploadFile, _downloadFile, value.logoImage)) : candid_none(),
        cemeteryInformation: value.cemeteryInformation,
        prayerForTheDeceased: value.prayerForTheDeceased,
        gravesDeclaration: value.gravesDeclaration,
        footer: value.footer,
        homepageHero: await to_candid_HomepageHeroContent_n64(_uploadFile, _downloadFile, value.homepageHero)
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GraveStatus): {
    free: null;
} | {
    paid: null;
} | {
    reserved: null;
} | {
    unpaid: null;
} {
    return value == GraveStatus.free ? {
        free: null
    } : value == GraveStatus.paid ? {
        paid: null
    } : value == GraveStatus.reserved ? {
        reserved: null
    } : value == GraveStatus.unpaid ? {
        unpaid: null
    } : value;
}
function to_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DeceasedPerson>): Array<_DeceasedPerson> {
    return value.map((x)=>to_candid_DeceasedPerson_n60(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
